/**
 * Copyright © 2019 DJI All Rights Reserved. 
 * 2020-05-09 Created
 * 
 */
package com.yifan.mybatisdemo.dao.entity.base;

import com.yifan.mybatisdemo.dto.base.BaseModel;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessagesExample extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messages
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messages
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public MessagesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messages
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> idCriteria;

        protected List<Criterion> messageCodeCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            idCriteria = new ArrayList<Criterion>();
            messageCodeCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getIdCriteria() {
            return idCriteria;
        }

        protected void addIdCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            idCriteria.add(new Criterion(condition, value, "com.yifan.mybatisdemo.dao.mapper.base.UUIDTypeHandler"));
            allCriteria = null;
        }

        protected void addIdCriterion(String condition, String value1, String value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            idCriteria.add(new Criterion(condition, value1, value2, "com.yifan.mybatisdemo.dao.mapper.base.UUIDTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getMessageCodeCriteria() {
            return messageCodeCriteria;
        }

        protected void addMessageCodeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            messageCodeCriteria.add(new Criterion(condition, value, "com.yifan.mybatisdemo.dao.mapper.base.UUIDTypeHandler"));
            allCriteria = null;
        }

        protected void addMessageCodeCriterion(String condition, String value1, String value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            messageCodeCriteria.add(new Criterion(condition, value1, value2, "com.yifan.mybatisdemo.dao.mapper.base.UUIDTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || idCriteria.size() > 0
                || messageCodeCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(idCriteria);
                allCriteria.addAll(messageCodeCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("\"id\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("\"id\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addIdCriterion("\"id\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addIdCriterion("\"id\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addIdCriterion("\"id\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addIdCriterion("\"id\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addIdCriterion("\"id\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addIdCriterion("\"id\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addIdCriterion("\"id\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addIdCriterion("\"id\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addIdCriterion("\"id\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addIdCriterion("\"id\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMessageCodeIsNull() {
            addCriterion("\"message_code\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageCodeIsNotNull() {
            addCriterion("\"message_code\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageCodeEqualTo(String value) {
            addMessageCodeCriterion("\"message_code\" =", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeNotEqualTo(String value) {
            addMessageCodeCriterion("\"message_code\" <>", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeGreaterThan(String value) {
            addMessageCodeCriterion("\"message_code\" >", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeGreaterThanOrEqualTo(String value) {
            addMessageCodeCriterion("\"message_code\" >=", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeLessThan(String value) {
            addMessageCodeCriterion("\"message_code\" <", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeLessThanOrEqualTo(String value) {
            addMessageCodeCriterion("\"message_code\" <=", value, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeIn(List<String> values) {
            addMessageCodeCriterion("\"message_code\" in", values, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeNotIn(List<String> values) {
            addMessageCodeCriterion("\"message_code\" not in", values, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeBetween(String value1, String value2) {
            addMessageCodeCriterion("\"message_code\" between", value1, value2, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageCodeNotBetween(String value1, String value2) {
            addMessageCodeCriterion("\"message_code\" not between", value1, value2, "messageCode");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIsNull() {
            addCriterion("\"message_type\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIsNotNull() {
            addCriterion("\"message_type\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageTypeEqualTo(Short value) {
            addCriterion("\"message_type\" =", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotEqualTo(Short value) {
            addCriterion("\"message_type\" <>", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeGreaterThan(Short value) {
            addCriterion("\"message_type\" >", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("\"message_type\" >=", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeLessThan(Short value) {
            addCriterion("\"message_type\" <", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeLessThanOrEqualTo(Short value) {
            addCriterion("\"message_type\" <=", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIn(List<Short> values) {
            addCriterion("\"message_type\" in", values, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotIn(List<Short> values) {
            addCriterion("\"message_type\" not in", values, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeBetween(Short value1, Short value2) {
            addCriterion("\"message_type\" between", value1, value2, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotBetween(Short value1, Short value2) {
            addCriterion("\"message_type\" not between", value1, value2, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageToIsNull() {
            addCriterion("\"message_to\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageToIsNotNull() {
            addCriterion("\"message_to\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageToEqualTo(String value) {
            addCriterion("\"message_to\" =", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToNotEqualTo(String value) {
            addCriterion("\"message_to\" <>", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToGreaterThan(String value) {
            addCriterion("\"message_to\" >", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToGreaterThanOrEqualTo(String value) {
            addCriterion("\"message_to\" >=", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToLessThan(String value) {
            addCriterion("\"message_to\" <", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToLessThanOrEqualTo(String value) {
            addCriterion("\"message_to\" <=", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToLike(String value) {
            addCriterion("\"message_to\" like", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToNotLike(String value) {
            addCriterion("\"message_to\" not like", value, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToIn(List<String> values) {
            addCriterion("\"message_to\" in", values, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToNotIn(List<String> values) {
            addCriterion("\"message_to\" not in", values, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToBetween(String value1, String value2) {
            addCriterion("\"message_to\" between", value1, value2, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageToNotBetween(String value1, String value2) {
            addCriterion("\"message_to\" not between", value1, value2, "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageTitleIsNull() {
            addCriterion("\"message_title\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageTitleIsNotNull() {
            addCriterion("\"message_title\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageTitleEqualTo(String value) {
            addCriterion("\"message_title\" =", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleNotEqualTo(String value) {
            addCriterion("\"message_title\" <>", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleGreaterThan(String value) {
            addCriterion("\"message_title\" >", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleGreaterThanOrEqualTo(String value) {
            addCriterion("\"message_title\" >=", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleLessThan(String value) {
            addCriterion("\"message_title\" <", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleLessThanOrEqualTo(String value) {
            addCriterion("\"message_title\" <=", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleLike(String value) {
            addCriterion("\"message_title\" like", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleNotLike(String value) {
            addCriterion("\"message_title\" not like", value, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleIn(List<String> values) {
            addCriterion("\"message_title\" in", values, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleNotIn(List<String> values) {
            addCriterion("\"message_title\" not in", values, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleBetween(String value1, String value2) {
            addCriterion("\"message_title\" between", value1, value2, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageTitleNotBetween(String value1, String value2) {
            addCriterion("\"message_title\" not between", value1, value2, "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNull() {
            addCriterion("\"message_content\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNotNull() {
            addCriterion("\"message_content\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageContentEqualTo(String value) {
            addCriterion("\"message_content\" =", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotEqualTo(String value) {
            addCriterion("\"message_content\" <>", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThan(String value) {
            addCriterion("\"message_content\" >", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThanOrEqualTo(String value) {
            addCriterion("\"message_content\" >=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThan(String value) {
            addCriterion("\"message_content\" <", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThanOrEqualTo(String value) {
            addCriterion("\"message_content\" <=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLike(String value) {
            addCriterion("\"message_content\" like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotLike(String value) {
            addCriterion("\"message_content\" not like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentIn(List<String> values) {
            addCriterion("\"message_content\" in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotIn(List<String> values) {
            addCriterion("\"message_content\" not in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentBetween(String value1, String value2) {
            addCriterion("\"message_content\" between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotBetween(String value1, String value2) {
            addCriterion("\"message_content\" not between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andIsSendIsNull() {
            addCriterion("\"is_send\" is null");
            return (Criteria) this;
        }

        public Criteria andIsSendIsNotNull() {
            addCriterion("\"is_send\" is not null");
            return (Criteria) this;
        }

        public Criteria andIsSendEqualTo(Short value) {
            addCriterion("\"is_send\" =", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotEqualTo(Short value) {
            addCriterion("\"is_send\" <>", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendGreaterThan(Short value) {
            addCriterion("\"is_send\" >", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendGreaterThanOrEqualTo(Short value) {
            addCriterion("\"is_send\" >=", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendLessThan(Short value) {
            addCriterion("\"is_send\" <", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendLessThanOrEqualTo(Short value) {
            addCriterion("\"is_send\" <=", value, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendIn(List<Short> values) {
            addCriterion("\"is_send\" in", values, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotIn(List<Short> values) {
            addCriterion("\"is_send\" not in", values, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendBetween(Short value1, Short value2) {
            addCriterion("\"is_send\" between", value1, value2, "isSend");
            return (Criteria) this;
        }

        public Criteria andIsSendNotBetween(Short value1, Short value2) {
            addCriterion("\"is_send\" not between", value1, value2, "isSend");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("\"send_time\" is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("\"send_time\" is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("\"send_time\" =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("\"send_time\" <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("\"send_time\" >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"send_time\" >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("\"send_time\" <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("\"send_time\" <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("\"send_time\" in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("\"send_time\" not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("\"send_time\" between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("\"send_time\" not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNull() {
            addCriterion("\"insert_time\" is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNotNull() {
            addCriterion("\"insert_time\" is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeEqualTo(Date value) {
            addCriterion("\"insert_time\" =", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotEqualTo(Date value) {
            addCriterion("\"insert_time\" <>", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThan(Date value) {
            addCriterion("\"insert_time\" >", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"insert_time\" >=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThan(Date value) {
            addCriterion("\"insert_time\" <", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
            addCriterion("\"insert_time\" <=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIn(List<Date> values) {
            addCriterion("\"insert_time\" in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotIn(List<Date> values) {
            addCriterion("\"insert_time\" not in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeBetween(Date value1, Date value2) {
            addCriterion("\"insert_time\" between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
            addCriterion("\"insert_time\" not between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertByIsNull() {
            addCriterion("\"insert_by\" is null");
            return (Criteria) this;
        }

        public Criteria andInsertByIsNotNull() {
            addCriterion("\"insert_by\" is not null");
            return (Criteria) this;
        }

        public Criteria andInsertByEqualTo(String value) {
            addCriterion("\"insert_by\" =", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByNotEqualTo(String value) {
            addCriterion("\"insert_by\" <>", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByGreaterThan(String value) {
            addCriterion("\"insert_by\" >", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByGreaterThanOrEqualTo(String value) {
            addCriterion("\"insert_by\" >=", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByLessThan(String value) {
            addCriterion("\"insert_by\" <", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByLessThanOrEqualTo(String value) {
            addCriterion("\"insert_by\" <=", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByLike(String value) {
            addCriterion("\"insert_by\" like", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByNotLike(String value) {
            addCriterion("\"insert_by\" not like", value, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByIn(List<String> values) {
            addCriterion("\"insert_by\" in", values, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByNotIn(List<String> values) {
            addCriterion("\"insert_by\" not in", values, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByBetween(String value1, String value2) {
            addCriterion("\"insert_by\" between", value1, value2, "insertBy");
            return (Criteria) this;
        }

        public Criteria andInsertByNotBetween(String value1, String value2) {
            addCriterion("\"insert_by\" not between", value1, value2, "insertBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("\"update_time\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("\"update_time\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("\"update_time\" =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("\"update_time\" <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("\"update_time\" >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("\"update_time\" >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("\"update_time\" <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("\"update_time\" <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("\"update_time\" in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("\"update_time\" not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("\"update_time\" between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("\"update_time\" not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("\"update_by\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("\"update_by\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("\"update_by\" =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("\"update_by\" <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("\"update_by\" >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("\"update_by\" >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("\"update_by\" <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("\"update_by\" <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("\"update_by\" like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("\"update_by\" not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("\"update_by\" in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("\"update_by\" not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("\"update_by\" between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("\"update_by\" not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andMessageToLikeInsensitive(String value) {
            addCriterion("upper(\"message_to\") like", value.toUpperCase(), "messageTo");
            return (Criteria) this;
        }

        public Criteria andMessageTitleLikeInsensitive(String value) {
            addCriterion("upper(\"message_title\") like", value.toUpperCase(), "messageTitle");
            return (Criteria) this;
        }

        public Criteria andMessageContentLikeInsensitive(String value) {
            addCriterion("upper(\"message_content\") like", value.toUpperCase(), "messageContent");
            return (Criteria) this;
        }

        public Criteria andInsertByLikeInsensitive(String value) {
            addCriterion("upper(\"insert_by\") like", value.toUpperCase(), "insertBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(\"update_by\") like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messages
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messages
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}