/**
 * Copyright © 2019 DJI All Rights Reserved. 
 * 2020-05-09 Created
 * 
 */
package com.yifan.mybatisdemo.dao.entity.base;

import java.util.Date;

/**
 * Database Table Remarks:
 *   消息发送记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table messages
 */
public class Messages extends BaseEntity {
    /**
     * Database Column Remarks:
     *   消息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   消息编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_code
     *
     * @mbg.generated
     */
    private String messageCode;

    /**
     * Database Column Remarks:
     *   消息类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_type
     *
     * @mbg.generated
     */
    private Short messageType;

    /**
     * Database Column Remarks:
     *   消息接收者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_to
     *
     * @mbg.generated
     */
    private String messageTo;

    /**
     * Database Column Remarks:
     *   消息标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_title
     *
     * @mbg.generated
     */
    private String messageTitle;

    /**
     * Database Column Remarks:
     *   消息内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.message_content
     *
     * @mbg.generated
     */
    private String messageContent;

    /**
     * Database Column Remarks:
     *   是否已经发送
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.is_send
     *
     * @mbg.generated
     */
    private Short isSend;

    /**
     * Database Column Remarks:
     *   定时发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.insert_by
     *
     * @mbg.generated
     */
    private String insertBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messages
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.id
     *
     * @return the value of messages.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withId(String id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.id
     *
     * @param id the value for messages.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_code
     *
     * @return the value of messages.message_code
     *
     * @mbg.generated
     */
    public String getMessageCode() {
        return messageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withMessageCode(String messageCode) {
        this.setMessageCode(messageCode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_code
     *
     * @param messageCode the value for messages.message_code
     *
     * @mbg.generated
     */
    public void setMessageCode(String messageCode) {
        this.messageCode = messageCode == null ? null : messageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_type
     *
     * @return the value of messages.message_type
     *
     * @mbg.generated
     */
    public Short getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withMessageType(Short messageType) {
        this.setMessageType(messageType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_type
     *
     * @param messageType the value for messages.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Short messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_to
     *
     * @return the value of messages.message_to
     *
     * @mbg.generated
     */
    public String getMessageTo() {
        return messageTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withMessageTo(String messageTo) {
        this.setMessageTo(messageTo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_to
     *
     * @param messageTo the value for messages.message_to
     *
     * @mbg.generated
     */
    public void setMessageTo(String messageTo) {
        this.messageTo = messageTo == null ? null : messageTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_title
     *
     * @return the value of messages.message_title
     *
     * @mbg.generated
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withMessageTitle(String messageTitle) {
        this.setMessageTitle(messageTitle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_title
     *
     * @param messageTitle the value for messages.message_title
     *
     * @mbg.generated
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.message_content
     *
     * @return the value of messages.message_content
     *
     * @mbg.generated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withMessageContent(String messageContent) {
        this.setMessageContent(messageContent);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.message_content
     *
     * @param messageContent the value for messages.message_content
     *
     * @mbg.generated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.is_send
     *
     * @return the value of messages.is_send
     *
     * @mbg.generated
     */
    public Short getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withIsSend(Short isSend) {
        this.setIsSend(isSend);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.is_send
     *
     * @param isSend the value for messages.is_send
     *
     * @mbg.generated
     */
    public void setIsSend(Short isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.send_time
     *
     * @return the value of messages.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withSendTime(Date sendTime) {
        this.setSendTime(sendTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.send_time
     *
     * @param sendTime the value for messages.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.insert_time
     *
     * @return the value of messages.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withInsertTime(Date insertTime) {
        this.setInsertTime(insertTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.insert_time
     *
     * @param insertTime the value for messages.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.insert_by
     *
     * @return the value of messages.insert_by
     *
     * @mbg.generated
     */
    public String getInsertBy() {
        return insertBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withInsertBy(String insertBy) {
        this.setInsertBy(insertBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.insert_by
     *
     * @param insertBy the value for messages.insert_by
     *
     * @mbg.generated
     */
    public void setInsertBy(String insertBy) {
        this.insertBy = insertBy == null ? null : insertBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.update_time
     *
     * @return the value of messages.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.update_time
     *
     * @param updateTime the value for messages.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.update_by
     *
     * @return the value of messages.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    public Messages withUpdateBy(String updateBy) {
        this.setUpdateBy(updateBy);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.update_by
     *
     * @param updateBy the value for messages.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Messages other = (Messages) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMessageCode() == null ? other.getMessageCode() == null : this.getMessageCode().equals(other.getMessageCode()))
            && (this.getMessageType() == null ? other.getMessageType() == null : this.getMessageType().equals(other.getMessageType()))
            && (this.getMessageTo() == null ? other.getMessageTo() == null : this.getMessageTo().equals(other.getMessageTo()))
            && (this.getMessageTitle() == null ? other.getMessageTitle() == null : this.getMessageTitle().equals(other.getMessageTitle()))
            && (this.getMessageContent() == null ? other.getMessageContent() == null : this.getMessageContent().equals(other.getMessageContent()))
            && (this.getIsSend() == null ? other.getIsSend() == null : this.getIsSend().equals(other.getIsSend()))
            && (this.getSendTime() == null ? other.getSendTime() == null : this.getSendTime().equals(other.getSendTime()))
            && (this.getInsertTime() == null ? other.getInsertTime() == null : this.getInsertTime().equals(other.getInsertTime()))
            && (this.getInsertBy() == null ? other.getInsertBy() == null : this.getInsertBy().equals(other.getInsertBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMessageCode() == null) ? 0 : getMessageCode().hashCode());
        result = prime * result + ((getMessageType() == null) ? 0 : getMessageType().hashCode());
        result = prime * result + ((getMessageTo() == null) ? 0 : getMessageTo().hashCode());
        result = prime * result + ((getMessageTitle() == null) ? 0 : getMessageTitle().hashCode());
        result = prime * result + ((getMessageContent() == null) ? 0 : getMessageContent().hashCode());
        result = prime * result + ((getIsSend() == null) ? 0 : getIsSend().hashCode());
        result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
        result = prime * result + ((getInsertTime() == null) ? 0 : getInsertTime().hashCode());
        result = prime * result + ((getInsertBy() == null) ? 0 : getInsertBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", messageCode=").append(messageCode);
        sb.append(", messageType=").append(messageType);
        sb.append(", messageTo=").append(messageTo);
        sb.append(", messageTitle=").append(messageTitle);
        sb.append(", messageContent=").append(messageContent);
        sb.append(", isSend=").append(isSend);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", insertBy=").append(insertBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append("]");
        return sb.toString();
    }
}