/**
 * Copyright © 2019 DJI All Rights Reserved. 
 * 2020-05-09 Created
 * 
 */
package com.yifan.mybatisdemo.dao.mapper.base;


import com.yifan.mybatisdemo.dao.entity.base.Messages;
import com.yifan.mybatisdemo.dao.entity.base.MessagesExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessagesBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    long countByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insert(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int insertSelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    List<Messages> selectByExampleWithRowbounds(MessagesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    List<Messages> selectByExample(MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    Messages selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Messages record, @Param("example") MessagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Messages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Messages record);

    /**
    /* This method was generated by dava-generator.
    */
//    default PageResp<Messages> selectByExampleWithPageResp(MessagesExample example) {
//        PageInfo<Messages> pageInfo = PageInfo.of(selectByExample(example));
//        PageResp<Messages> pageResp = new PageResp<>();
//        pageResp.setCurrentPage(pageInfo.getPageNum());
//        pageResp.setDatas(pageInfo.getList());
//        pageResp.setPageSize(pageInfo.getSize());
//        pageResp.setTotalCount(pageInfo.getTotal());
//        pageResp.setTotalPages(pageInfo.getPages());
//        pageResp.setStartIndex(pageInfo.getStartRow());
//        return pageResp;
//    }
}